version: "1.0"
defaults:
  base_dir: ../worktrees/lak

hooks:
  post_create:
    - type: copy
      from: .claude
      to: .claude
    - type: command
      command: mise trust
    - type: command
      command: lefthook install
